import type { Subscription } from './data/types';

export type DisputeReason =
  | 'forgotten-trial'
  | 'auto-renewal-no-notice'
  | 'cancelled-still-charged'
  | 'unauthorized-charge'
  | 'price-hike-no-notice';

export const DISPUTE_REASONS: { value: DisputeReason; label: string; subtext: string }[] = [
  { value: 'forgotten-trial', label: 'Trial converted without notice', subtext: 'Free trial silently became a paid charge' },
  { value: 'auto-renewal-no-notice', label: 'Auto-renewed without warning', subtext: 'Annual or monthly renewal not disclosed' },
  { value: 'cancelled-still-charged', label: 'Cancelled but still charged', subtext: 'Service was cancelled — charge still appeared' },
  { value: 'unauthorized-charge', label: 'I never authorized this', subtext: 'No record of signing up' },
  { value: 'price-hike-no-notice', label: 'Price raised without notice', subtext: 'New price was not disclosed in advance' },
];

const REASON_PHRASES: Record<DisputeReason, string> = {
  'forgotten-trial':
    'The charge stems from a free trial that converted into a paid subscription without clear, conspicuous notice as required under the Restore Online Shoppers\' Confidence Act (ROSCA, 15 U.S.C. § 8403).',
  'auto-renewal-no-notice':
    'The renewal was processed without advance notification, in conflict with California\'s Automatic Renewal Law (Cal. Bus. & Prof. Code §§ 17600–17606) and equivalent statutes in 22 other states.',
  'cancelled-still-charged':
    'I cancelled this service prior to the billing date, yet the charge still appeared on my statement. Under the Electronic Fund Transfer Act (15 U.S.C. § 1693f), unauthorized post-cancellation debits must be reversed.',
  'unauthorized-charge':
    'I have no record of authorizing this subscription. Under 12 C.F.R. § 1005.6 (Regulation E), this constitutes an unauthorized electronic fund transfer and must be refunded.',
  'price-hike-no-notice':
    'The price was raised without the legally required 30-day advance notice. Under the FTC\'s Negative Option Rule, material changes to subscription terms require affirmative consent.',
};

export type DisputeForm = {
  fullName: string;
  email: string;
  chargeDate: string;
  amount: number;
  reason: DisputeReason;
  referenceNumber?: string;
};

export function generateDisputeLetter(sub: Subscription, form: DisputeForm): string {
  const today = new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }).format(new Date());
  const reasonText = REASON_PHRASES[form.reason];
  const amountStr = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(form.amount);
  const ref = form.referenceNumber ? `\nReference / Transaction ID: ${form.referenceNumber}` : '';

  return `${today}

${sub.vendor}
Billing Disputes Department
Re: Refund request — ${sub.name}

To Whom It May Concern,

I am writing to formally dispute a charge of ${amountStr} dated ${form.chargeDate}, billed to my account by ${sub.vendor} for "${sub.name}".${ref}

${reasonText}

Accordingly, I respectfully request a full refund of ${amountStr} to the original payment method within 10 business days of receipt of this letter. Please confirm in writing once the refund has been processed.

If a refund is not issued within that window, I will pursue the matter further through:
  • A formal chargeback request with my card issuer under Regulation Z (15 U.S.C. § 1666).
  • A complaint filed with the Federal Trade Commission (ftc.gov/complaint).
  • A complaint filed with the Consumer Financial Protection Bureau (consumerfinance.gov/complaint).
  • A complaint filed with my state Attorney General's office.

I trust this can be resolved amicably and promptly. I appreciate your attention to this matter.

Sincerely,

${form.fullName}
${form.email}

— Generated by Phantom on behalf of ${form.fullName}. Phantom does not file disputes on the user's behalf without explicit authorization.`;
}
