import Foundation
import SwiftUI

/// Maps a subscription / merchant to its bundled brand SVG (in Resources/Brands/)
/// and its official brand color. SVG files come from simple-icons.org (CC0).
enum BrandRegistry {
    /// Returns `(svgFileName, hexColor)` for a known merchant, or nil if we should
    /// fall back to the letter avatar.
    static func brand(for subId: String, fallbackName: String) -> Brand? {
        // First try direct id match
        if let b = byId[subId.lowercased()] { return b }
        // Then try matching the human name against known patterns
        let n = fallbackName.lowercased()
        for (pattern, brand) in patternMatches {
            if n.contains(pattern) { return brand }
        }
        return nil
    }

    struct Brand: Equatable {
        let svgName: String        // file in Resources/Brands without .svg
        let hex: String            // official brand hex
        let backgroundHex: String? // optional contrasting background; nil → uses hex with 12% opacity
    }

    // Compact registry — keys MUST match the SVG filenames in Resources/Brands/
    static let byId: [String: Brand] = [
        "netflix":              Brand(svgName: "netflix", hex: "E50914", backgroundHex: "000000"),
        "hulu":                 Brand(svgName: "hulu", hex: "1CE783", backgroundHex: "0B0C0F"),
        "spotify":              Brand(svgName: "spotify", hex: "1DB954", backgroundHex: "191414"),
        "peacock":              Brand(svgName: "peacock", hex: "FA6400", backgroundHex: nil),
        "paramount":            Brand(svgName: "paramount", hex: "0064FF", backgroundHex: nil),
        "hbo-max":              Brand(svgName: "hbo-max", hex: "0046FF", backgroundHex: "000000"),
        "apple-tv":             Brand(svgName: "apple-tv", hex: "000000", backgroundHex: "FFFFFF"),
        "apple-music":          Brand(svgName: "apple-music", hex: "FA243C", backgroundHex: nil),
        "tidal":                Brand(svgName: "tidal", hex: "000000", backgroundHex: nil),
        "audible":              Brand(svgName: "audible", hex: "F8991C", backgroundHex: nil),
        "amazon-prime":         Brand(svgName: "amazon-prime", hex: "00A8E1", backgroundHex: nil),
        "walmart-plus":         Brand(svgName: "walmart-plus", hex: "0071CE", backgroundHex: nil),
        "icloud":               Brand(svgName: "icloud", hex: "3693F3", backgroundHex: nil),
        "google-one":           Brand(svgName: "google-one", hex: "4285F4", backgroundHex: nil),
        "dropbox":              Brand(svgName: "dropbox", hex: "0061FF", backgroundHex: nil),
        "adobe-cc":             Brand(svgName: "adobe-cc", hex: "FF0000", backgroundHex: "000000"),
        "adobe-photography":    Brand(svgName: "adobe-photography", hex: "FF0000", backgroundHex: nil),
        "github":               Brand(svgName: "github", hex: "181717", backgroundHex: nil),
        "github-copilot":       Brand(svgName: "github-copilot", hex: "181717", backgroundHex: nil),
        "chatgpt":              Brand(svgName: "openai", hex: "10A37F", backgroundHex: nil),
        "openai":               Brand(svgName: "openai", hex: "10A37F", backgroundHex: nil),
        "claude":               Brand(svgName: "claude", hex: "D97757", backgroundHex: nil),
        "anthropic":            Brand(svgName: "anthropic", hex: "191919", backgroundHex: nil),
        "gemini":               Brand(svgName: "gemini", hex: "4285F4", backgroundHex: nil),
        "perplexity":           Brand(svgName: "perplexity", hex: "20808D", backgroundHex: nil),
        "cursor":               Brand(svgName: "cursor", hex: "000000", backgroundHex: nil),
        "replit":               Brand(svgName: "replit", hex: "F26207", backgroundHex: nil),
        "vercel":               Brand(svgName: "vercel", hex: "000000", backgroundHex: nil),
        "v0":                   Brand(svgName: "v0", hex: "000000", backgroundHex: nil),
        "bolt":                 Brand(svgName: "bolt", hex: "000000", backgroundHex: nil),
        "lovable":              Brand(svgName: "lovable", hex: "EF4444", backgroundHex: nil),
        "linear":               Brand(svgName: "linear", hex: "5E6AD2", backgroundHex: nil),
        "suno":                 Brand(svgName: "suno", hex: "000000", backgroundHex: nil),
        "elevenlabs":           Brand(svgName: "elevenlabs", hex: "000000", backgroundHex: nil),
        "huggingface":          Brand(svgName: "huggingface", hex: "FFD21E", backgroundHex: "000000"),
        "deepseek":             Brand(svgName: "deepseek", hex: "4D6BFE", backgroundHex: nil),
        "notion":               Brand(svgName: "notion", hex: "000000", backgroundHex: "F4F4F5"),
        "duolingo":             Brand(svgName: "duolingo", hex: "58CC02", backgroundHex: nil),
        "lastpass":             Brand(svgName: "lastpass", hex: "D32D27", backgroundHex: nil),
        "1password":            Brand(svgName: "1password", hex: "3B66BC", backgroundHex: nil),
        "expressvpn":           Brand(svgName: "expressvpn", hex: "DA3940", backgroundHex: nil),
        "nordvpn":              Brand(svgName: "nordvpn", hex: "4687FF", backgroundHex: nil),
        "nyt":                  Brand(svgName: "nyt", hex: "000000", backgroundHex: "FFFFFF"),
        "peloton":              Brand(svgName: "peloton", hex: "DF1B2C", backgroundHex: nil),
        "headspace":            Brand(svgName: "headspace", hex: "F47D31", backgroundHex: nil),
        "youtube-premium":      Brand(svgName: "youtube-premium", hex: "FF0000", backgroundHex: "FFFFFF"),
        "youtube-tv":           Brand(svgName: "youtube-tv", hex: "FF0000", backgroundHex: "FFFFFF"),
        "paramount-plus":       Brand(svgName: "paramount", hex: "0064FF", backgroundHex: nil),
        // Mobility / delivery subscription tiers — the *Pass / *One / *Pink
        // memberships that ride on top of the ride/food apps.
        "uber-one":             Brand(svgName: "uber", hex: "000000", backgroundHex: nil),
        "lyft-pink":            Brand(svgName: "lyft", hex: "FF00BF", backgroundHex: nil),
        "dashpass":             Brand(svgName: "doordash", hex: "EB1700", backgroundHex: nil),
        // No-SVG subscription brands — recognized so looksLikeSubscription
        // returns true via the brand-match path. Avatar falls back to the
        // first-letter glyph on the brand-coloured background.
        "planet-fitness":       Brand(svgName: "planet-fitness-missing", hex: "5A1B5A", backgroundHex: nil),
        "equinox":              Brand(svgName: "equinox-missing", hex: "000000", backgroundHex: nil),
        "masterclass":          Brand(svgName: "masterclass-missing", hex: "C8102E", backgroundHex: nil),
        "wsj":                  Brand(svgName: "wsj-missing", hex: "000000", backgroundHex: nil),
        "washington-post":      Brand(svgName: "washington-post-missing", hex: "000000", backgroundHex: nil),
        "sirius-xm":            Brand(svgName: "sirius-missing", hex: "0033A0", backgroundHex: nil),
        "calm":                 Brand(svgName: "calm-missing", hex: "1A7DEF", backgroundHex: nil),
        "noom":                 Brand(svgName: "noom-missing", hex: "FF7E00", backgroundHex: nil),
        "disney-plus":          Brand(svgName: "disney-missing", hex: "113CCF", backgroundHex: "000000"),
        // Cable / internet / wireless — recognized as subs so they appear on
        // Radar; svgs fall back to a letter avatar on the brand color.
        "spectrum":             Brand(svgName: "spectrum", hex: "0099D8", backgroundHex: nil),
        "xfinity":              Brand(svgName: "xfinity-missing", hex: "000000", backgroundHex: nil),
        "t-mobile":             Brand(svgName: "tmobile-missing", hex: "E20074", backgroundHex: nil),
        // (verizon / att continue below)
        "verizon":              Brand(svgName: "verizon", hex: "CD040B", backgroundHex: nil),
        "att":                  Brand(svgName: "att-missing", hex: "00A8E0", backgroundHex: nil),
        // Platform billers — the statement only says APPLE.COM/BILL or GOOGLE *,
        // so we can't name the product. Recognised as subs; the detail view
        // points at Settings › Subscriptions / Play Store instead of a vendor.
        "apple-services":       Brand(svgName: "apple-services-missing", hex: "000000", backgroundHex: nil),
        "apple-one":            Brand(svgName: "apple-one-missing", hex: "000000", backgroundHex: nil),
        "apple-arcade":         Brand(svgName: "apple-arcade-missing", hex: "000000", backgroundHex: nil),
        "apple-news":           Brand(svgName: "apple-news-missing", hex: "FA243C", backgroundHex: nil),
        "apple-fitness":        Brand(svgName: "apple-fitness-missing", hex: "000000", backgroundHex: nil),
        "google-play":          Brand(svgName: "google-play-missing", hex: "34A853", backgroundHex: nil),
        "google-workspace":     Brand(svgName: "google-workspace-missing", hex: "4285F4", backgroundHex: nil),
        "microsoft-365":        Brand(svgName: "microsoft-365-missing", hex: "D83B01", backgroundHex: nil),
        "adobe":                Brand(svgName: "adobe-missing", hex: "FF0000", backgroundHex: nil),
        "midjourney":           Brand(svgName: "midjourney-missing", hex: "000000", backgroundHex: nil),
        "runway":               Brand(svgName: "runway-missing", hex: "000000", backgroundHex: nil),
        "mistral":              Brand(svgName: "mistral-missing", hex: "FF7000", backgroundHex: nil),
        "cohere":               Brand(svgName: "cohere-missing", hex: "39594D", backgroundHex: nil),
        "prime-video":          Brand(svgName: "amazon-prime", hex: "00A8E1", backgroundHex: nil),
        "amazon-music":         Brand(svgName: "amazon-music-missing", hex: "25D1DA", backgroundHex: nil),
        "kindle-unlimited":     Brand(svgName: "kindle-missing", hex: "FF9900", backgroundHex: nil),
        "amazon-digital":       Brand(svgName: "amazon-digital-missing", hex: "FF9900", backgroundHex: nil),
        "youtube-music":        Brand(svgName: "youtube-premium", hex: "FF0000", backgroundHex: "FFFFFF"),
        "instacart-plus":       Brand(svgName: "instacart-missing", hex: "43B02A", backgroundHex: nil),
        "grubhub-plus":         Brand(svgName: "grubhub-missing", hex: "F63440", backgroundHex: nil),
        "crunchyroll":          Brand(svgName: "crunchyroll-missing", hex: "F47521", backgroundHex: nil),
        "espn-plus":            Brand(svgName: "espn-missing", hex: "D00000", backgroundHex: nil),
        "starz":                Brand(svgName: "starz-missing", hex: "000000", backgroundHex: nil),
        "amc-plus":             Brand(svgName: "amc-missing", hex: "000000", backgroundHex: nil),
        "fubo":                 Brand(svgName: "fubo-missing", hex: "FF6B00", backgroundHex: nil),
        "sling":                Brand(svgName: "sling-missing", hex: "0F6FFF", backgroundHex: nil),
        "philo":                Brand(svgName: "philo-missing", hex: "00A8E1", backgroundHex: nil),
        "pandora":              Brand(svgName: "pandora-missing", hex: "3668FF", backgroundHex: nil),
        "bitwarden":            Brand(svgName: "bitwarden-missing", hex: "175DDC", backgroundHex: nil),
        "proton-vpn":           Brand(svgName: "proton-missing", hex: "6D4AFF", backgroundHex: nil),
        "proton":               Brand(svgName: "proton-missing", hex: "6D4AFF", backgroundHex: nil),
        "apple-passwords":      Brand(svgName: "apple-passwords-missing", hex: "000000", backgroundHex: nil),
    ]

    /// Fuzzy fallback — checks the human-readable name for these substrings.
    static let patternMatches: [(String, Brand)] = [
        ("netflix",        Brand(svgName: "netflix", hex: "E50914", backgroundHex: "000000")),
        ("hulu",           Brand(svgName: "hulu", hex: "1CE783", backgroundHex: "0B0C0F")),
        ("spotify",        Brand(svgName: "spotify", hex: "1DB954", backgroundHex: "191414")),
        ("disney+",        Brand(svgName: "youtube-premium", hex: "113CCF", backgroundHex: nil)), // no disney svg, repurpose
        ("peacock",        Brand(svgName: "peacock", hex: "FA6400", backgroundHex: nil)),
        ("paramount",      Brand(svgName: "paramount", hex: "0064FF", backgroundHex: nil)),
        ("hbo",            Brand(svgName: "hbo-max", hex: "0046FF", backgroundHex: "000000")),
        ("max ",           Brand(svgName: "hbo-max", hex: "0046FF", backgroundHex: "000000")),
        ("youtube tv",     Brand(svgName: "youtube-tv", hex: "FF0000", backgroundHex: "FFFFFF")),
        ("youtube",        Brand(svgName: "youtube-premium", hex: "FF0000", backgroundHex: "FFFFFF")),
        ("apple tv",       Brand(svgName: "apple-tv", hex: "000000", backgroundHex: "FFFFFF")),
        ("apple music",    Brand(svgName: "apple-music", hex: "FA243C", backgroundHex: nil)),
        ("icloud",         Brand(svgName: "icloud", hex: "3693F3", backgroundHex: nil)),
        ("amazon prime",   Brand(svgName: "amazon-prime", hex: "00A8E1", backgroundHex: nil)),
        ("audible",        Brand(svgName: "audible", hex: "F8991C", backgroundHex: nil)),
        ("sirius",         Brand(svgName: "audible", hex: "0033A0", backgroundHex: nil)), // no sirius svg, fallback
        ("adobe creative", Brand(svgName: "adobe-cc", hex: "FF0000", backgroundHex: "000000")),
        ("adobe",          Brand(svgName: "adobe-photography", hex: "FF0000", backgroundHex: nil)),
        ("microsoft",      Brand(svgName: "microsoft-365-missing", hex: "D83B01", backgroundHex: nil)),
        ("github",         Brand(svgName: "github", hex: "181717", backgroundHex: nil)),
        ("chatgpt",        Brand(svgName: "openai",  hex: "10A37F", backgroundHex: nil)),
        ("openai",         Brand(svgName: "openai",  hex: "10A37F", backgroundHex: nil)),
        ("anthropic",      Brand(svgName: "anthropic", hex: "191919", backgroundHex: nil)),
        ("claude",         Brand(svgName: "claude",  hex: "D97757", backgroundHex: nil)),
        ("gemini",         Brand(svgName: "gemini",  hex: "4285F4", backgroundHex: nil)),
        ("perplexity",     Brand(svgName: "perplexity", hex: "20808D", backgroundHex: nil)),
        ("cursor",         Brand(svgName: "cursor",  hex: "000000", backgroundHex: nil)),
        ("replit",         Brand(svgName: "replit",  hex: "F26207", backgroundHex: nil)),
        ("v0.dev",         Brand(svgName: "v0",      hex: "000000", backgroundHex: nil)),
        ("vercel",         Brand(svgName: "vercel",  hex: "000000", backgroundHex: nil)),
        ("bolt.new",       Brand(svgName: "bolt",    hex: "000000", backgroundHex: nil)),
        ("stackblitz",     Brand(svgName: "bolt",    hex: "000000", backgroundHex: nil)),
        ("lovable",        Brand(svgName: "lovable", hex: "EF4444", backgroundHex: nil)),
        ("linear",         Brand(svgName: "linear",  hex: "5E6AD2", backgroundHex: nil)),
        ("midjourney",     Brand(svgName: "midjourney-missing", hex: "000000", backgroundHex: nil)),
        ("runway",         Brand(svgName: "runway-missing", hex: "000000", backgroundHex: nil)),
        ("suno",           Brand(svgName: "suno",    hex: "000000", backgroundHex: nil)),
        ("elevenlabs",     Brand(svgName: "elevenlabs", hex: "000000", backgroundHex: nil)),
        ("eleven labs",    Brand(svgName: "elevenlabs", hex: "000000", backgroundHex: nil)),
        ("huggingface",    Brand(svgName: "huggingface", hex: "FFD21E", backgroundHex: "000000")),
        ("hugging face",   Brand(svgName: "huggingface", hex: "FFD21E", backgroundHex: "000000")),
        ("deepseek",       Brand(svgName: "deepseek", hex: "4D6BFE", backgroundHex: nil)),
        ("mistral",        Brand(svgName: "mistral-missing", hex: "FF7000", backgroundHex: nil)),
        ("cohere",         Brand(svgName: "cohere-missing", hex: "39594D", backgroundHex: nil)),
        ("notion",         Brand(svgName: "notion", hex: "000000", backgroundHex: "F4F4F5")),
        ("dropbox",        Brand(svgName: "dropbox", hex: "0061FF", backgroundHex: nil)),
        ("duolingo",       Brand(svgName: "duolingo", hex: "58CC02", backgroundHex: nil)),
        ("lastpass",       Brand(svgName: "lastpass", hex: "D32D27", backgroundHex: nil)),
        ("1password",      Brand(svgName: "1password", hex: "3B66BC", backgroundHex: nil)),
        ("expressvpn",     Brand(svgName: "expressvpn", hex: "DA3940", backgroundHex: nil)),
        ("nordvpn",        Brand(svgName: "nordvpn", hex: "4687FF", backgroundHex: nil)),
        ("new york times", Brand(svgName: "nyt", hex: "000000", backgroundHex: "FFFFFF")),
        ("peloton",        Brand(svgName: "peloton", hex: "DF1B2C", backgroundHex: nil)),
        ("headspace",      Brand(svgName: "headspace", hex: "F47D31", backgroundHex: nil)),
        ("walmart",        Brand(svgName: "walmart-plus", hex: "0071CE", backgroundHex: nil)),
        ("uber one",       Brand(svgName: "uber", hex: "000000", backgroundHex: nil)),
        ("uber *one",      Brand(svgName: "uber", hex: "000000", backgroundHex: nil)),
        ("lyft pink",      Brand(svgName: "lyft", hex: "FF00BF", backgroundHex: nil)),
        ("lyft *pink",     Brand(svgName: "lyft", hex: "FF00BF", backgroundHex: nil)),
        ("dashpass",       Brand(svgName: "doordash", hex: "EB1700", backgroundHex: nil)),
    ]

    /// Clean, brand-aware display name for a given brand id. Used by the
    /// Radar / Negotiate / Alerts list views to show "Netflix" / "Apple
    /// Music" / "YouTube Premium" instead of the raw bank-statement text
    /// ("APL*APPLE MUSIC" / "GOOGLE *Youtube Musi G.CO/Helppay#"). Returns
    /// nil when the brand id is unknown — the caller should fall back to
    /// the normalized merchant text.
    ///
    /// The map is hand-curated so we can preserve acronym casing (NYT,
    /// WSJ, HBO) and brand-correct casing (YouTube, GitHub, iCloud,
    /// 1Password) that a naive title-case wouldn't produce.
    static func displayName(for brandId: String) -> String? {
        knownDisplayNames[brandId.lowercased()]
    }

    static var allDisplayNames: [String] { Array(knownDisplayNames.values) }

    /// Best-guess product category for a known brand id. Drives same-category
    /// overlap in the zombie score (e.g. three streaming subs flag each other).
    /// Unknown brands fall back to `.other`, which is intentionally excluded from
    /// overlap so we don't imply two unrelated "Other" charges are duplicates.
    static func category(for brandId: String) -> Category {
        knownCategories[brandId.lowercased()] ?? .other
    }

    /// Fine-grained kind for a brand id. Drives overlap (only same-kind subs are
    /// substitutes), bundle coverage and the cheaper-plan finder. Unknown
    /// brands are `.other`, which never overlaps.
    static func kind(for brandId: String) -> Kind {
        knownKinds[brandId.lowercased()] ?? .other
    }

    /// Every brand id the pipeline can emit that has a kind. Exposed for tests
    /// so the catalog and the registry can be checked for drift.
    static var knownBrandIds: Set<String> { Set(knownKinds.keys) }

    private static let knownKinds: [String: Kind] = [
        // Video on demand
        "netflix": .video, "hulu": .video, "peacock": .video, "paramount": .video,
        "paramount-plus": .video, "disney-plus": .video, "hbo-max": .video, "apple-tv": .video,
        "prime-video": .video, "espn-plus": .video, "starz": .video, "amc-plus": .video,
        "crunchyroll": .video,
        // Live TV
        "youtube-tv": .liveTV, "sling": .liveTV, "fubo": .liveTV, "philo": .liveTV,
        // Music
        "spotify": .music, "apple-music": .music, "tidal": .music, "youtube-music": .music,
        "amazon-music": .music, "sirius-xm": .music, "pandora": .music,
        // YouTube Premium is filed as music: it substitutes for Spotify (via YouTube
        // Music), not for Netflix. Overlap follows that, and so does the catalog.
        "youtube-premium": .music,
        // Audiobooks & reading
        "audible": .audiobooks, "kindle-unlimited": .audiobooks,
        // News
        "nyt": .news, "wsj": .news, "washington-post": .news, "apple-news": .news,
        // Cloud storage
        "icloud": .cloudStorage, "google-one": .cloudStorage, "dropbox": .cloudStorage,
        // Passwords / VPN
        "1password": .passwordManager, "lastpass": .passwordManager, "bitwarden": .passwordManager,
        "apple-passwords": .passwordManager,
        "expressvpn": .vpn, "nordvpn": .vpn, "proton-vpn": .vpn,
        // AI
        "chatgpt": .aiAssistant, "openai": .aiAssistant, "claude": .aiAssistant, "anthropic": .aiAssistant,
        "gemini": .aiAssistant, "perplexity": .aiAssistant, "deepseek": .aiAssistant,
        "mistral": .aiAssistant, "cohere": .aiAssistant,
        "github-copilot": .aiCoding, "cursor": .aiCoding, "replit": .aiCoding, "v0": .aiCoding,
        "bolt": .aiCoding, "lovable": .aiCoding,
        // Dev / productivity / creative / learning
        "github": .devTools, "vercel": .devTools, "linear": .devTools, "huggingface": .devTools,
        "notion": .productivity, "microsoft-365": .productivity, "google-workspace": .productivity,
        "adobe-cc": .creative, "adobe-photography": .creative, "adobe": .creative,
        "suno": .creative, "elevenlabs": .creative, "midjourney": .creative, "runway": .creative,
        "duolingo": .learning, "masterclass": .learning,
        // Fitness / wellness
        "peloton": .fitness, "planet-fitness": .fitness, "equinox": .fitness, "apple-fitness": .fitness,
        "headspace": .meditation, "calm": .meditation,
        // Memberships
        "dashpass": .delivery, "uber-one": .delivery, "lyft-pink": .delivery,
        "instacart-plus": .delivery, "grubhub-plus": .delivery,
        "amazon-prime": .retailMembership, "walmart-plus": .retailMembership,
        // Telecom
        "spectrum": .telecom, "xfinity": .telecom, "t-mobile": .telecom, "verizon": .telecom, "att": .telecom,
        // Gaming
        "apple-arcade": .gaming,
        // Platform-billed (product unknown) + Apple One (a bundle, not a substitute)
        "apple-services": .platformBilled, "google-play": .platformBilled, "amazon-digital": .platformBilled,
        "apple-one": .other, "proton": .other,
        "noom": .health,
        // Verticals added 2026-09-11.
        "abcmouse": .kids, "acorn-tv": .video, "arlo": .homeSecurity, "aura": .security,
        "betterhelp": .health, "bitdefender": .security, "blinkist": .audiobooks,
        "bloomberg": .news, "blue-apron": .mealKit, "bluehost": .webHosting, "britbox": .video,
        "bumble": .dating, "calendly": .productivity, "canva": .creative, "capcut": .creative,
        "classpass": .fitness, "coffee-meets-bagel": .dating, "cookunity": .mealKit,
        "copilot-money": .finance, "costco": .retailMembership, "criterion-channel": .video,
        "curiositystream": .video, "cvs-carepass": .retailMembership, "dazn": .sports,
        "deezer": .music, "deleteme": .security, "descript": .creative,
        "discord-nitro": .socialMedia, "epic-books": .kids, "everand": .audiobooks,
        "evernote": .productivity, "factor": .mealKit, "fastmail": .email, "figma": .creative,
        "financial-times": .news, "fitbit-premium": .fitness, "framer": .webHosting,
        "geforce-now": .gaming, "godaddy": .webHosting, "grammarly": .productivity,
        "green-chef": .mealKit, "grindr": .dating, "hellofresh": .mealKit, "hers": .health,
        "hims": .health, "hinge": .dating, "home-chef": .mealKit, "hostinger": .webHosting,
        "incogni": .security, "ko-fi": .creatorSupport, "libro-fm": .audiobooks,
        "lifelock": .security, "linkedin-premium": .socialMedia, "malwarebytes": .security,
        "marley-spoon": .mealKit, "match": .dating, "mcafee": .security, "mister-car-wash": .auto,
        "mlb-tv": .sports, "monarch-money": .finance, "morningstar": .finance, "mubi": .video,
        "namecheap": .webHosting, "nba-league-pass": .sports, "nebula": .video,
        "nest-aware": .homeSecurity, "nfl-plus": .sports, "nintendo-switch-online": .gaming,
        "noggin": .kids, "norton": .security, "one-medical": .health, "onstar": .auto,
        "otter-ai": .productivity, "oura": .fitness, "patreon": .creatorSupport,
        "pixelmator": .creative, "playstation-plus": .gaming, "proton-mail": .email,
        "qobuz": .music, "quickbooks": .finance, "quicken-simplifi": .finance,
        "readwise": .productivity, "reddit-premium": .socialMedia, "ring-home": .homeSecurity,
        "roblox-premium": .gaming, "rocket-money": .finance, "sams-club": .retailMembership,
        "seeking-alpha": .finance, "shopify": .webHosting, "shudder": .video,
        "simplisafe": .homeSecurity, "snapchat-plus": .socialMedia, "speechify": .audiobooks,
        "squarespace": .webHosting, "strava": .fitness, "substack": .creatorSupport,
        "superhuman": .productivity, "take-5-car-wash": .auto, "talkspace": .health,
        "the-athletic": .news, "the-atlantic": .news, "the-economist": .news,
        "the-new-yorker": .news, "tinder": .dating, "todoist": .productivity, "turbotax": .finance,
        "twitch": .creatorSupport, "webflow": .webHosting, "weight-watchers": .health,
        "whoop": .fitness, "wix": .webHosting, "wordpress": .webHosting, "wyze": .homeSecurity,
        "xbox-game-pass": .gaming, "ynab": .finance, "zips-car-wash": .auto,
        // Catalog merge 2026-09-11.
        "tubi": .video,
        "pluto-tv": .video,
        "roku-channel": .video,
        "kanopy": .video,
        "hoopla": .video,
        "magellantv": .video,
        "dropout": .video,
        "hallmark-plus": .video,
        "nordpass": .passwordManager,
        "dashlane": .passwordManager,
        "affinity": .creative,
        "davinci-resolve": .creative,
        "nike-training-club": .fitness,
        "google-news": .news,
        "proton-pass": .passwordManager,
        "libby": .audiobooks,
        "insight-timer": .meditation,
        "microsoft-copilot": .aiAssistant,
        "windsurf": .aiCoding,
        "babbel": .learning,
        "busuu": .learning,
        "mullvad": .vpn,
        "skillshare": .learning,
        "weightwatchers": .health,
        "obsidian": .productivity,
        "iheartradio": .music,
        // Catalog merge 2026-09-11.
        "waking-up": .meditation,
        "ten-percent-happier": .meditation,
        "balance": .meditation,
        "x-premium": .socialMedia,
        "meta-verified": .socialMedia,
        "telegram-premium": .socialMedia,
        "medium": .creatorSupport,
        "open-path-collective": .health,
        "psychology-today-finder": .health,
        "dinnerly": .mealKit,
        "okcupid": .dating,
        "peloton-app": .fitness,
        "slack": .socialMedia,
        "scruff": .dating,
        "feeld": .dating,
        "everyplate": .mealKit,
        "tasty": .mealKit,
        "goodrx": .health,
        "cost-plus-drugs": .health,
        "buy-me-a-coffee": .creatorSupport,
        "indeed": .socialMedia,
        "glassdoor": .socialMedia,
        "feedly": .creatorSupport,
        "cvs-minuteclinic": .health,
        "apple-watch": .fitness,
        "google-health-premium": .fitness,
        "youtube": .creatorSupport,
        "brave-browser": .socialMedia,
        "discord": .socialMedia,
        "instagram": .socialMedia,
        "bereal": .socialMedia,
        "nike-run-club": .fitness,
        "garmin-connect": .fitness,
        "signal": .socialMedia,
        "whatsapp": .socialMedia,
        "kick": .creatorSupport,
        "myfitnesspal": .health,
        "bluesky": .socialMedia,
        "threads": .socialMedia,
        "mastodon": .socialMedia,
        // Catalog merge 2026-09-11.
        "tesla-premium-connectivity": .auto,
        "lingokids": .kids,
        "homer": .kids,
        "bjs": .retailMembership,
        "target-circle-360": .retailMembership,
        "khan-academy-kids": .kids,
        "pbs-kids": .kids,
        "eufy": .homeSecurity,
        "cvs-extracare": .retailMembership,
        "aaa": .auto,
        "adt": .homeSecurity,
        "target-circle": .retailMembership,
        "tesla-standard-connectivity": .auto,
        // Catalog merge 2026-09-11.
        "hey": .email,
        "tuta": .email,
        "simplelogin": .email,
        "free-credit-freeze": .security,
        "builtin-os-protection": .security,
        "empower": .finance,
        "ca-drop": .security,
        "gmail": .email,
        "credit-karma": .security,
        "yahoo-finance": .finance,
        "fidelity": .finance,
        "firefox-relay": .email,
        "freetaxusa": .finance,
        "cash-app-taxes": .finance,
        "irs-free-file": .finance,
    ]

    private static let knownCategories: [String: Category] = [
        // Entertainment — streaming, music, audio
        "netflix": .entertainment, "hulu": .entertainment, "spotify": .entertainment,
        "peacock": .entertainment, "paramount": .entertainment, "paramount-plus": .entertainment,
        "disney-plus": .entertainment, "hbo-max": .entertainment, "apple-tv": .entertainment,
        "apple-music": .entertainment, "tidal": .entertainment, "audible": .entertainment,
        "youtube-premium": .entertainment, "youtube-tv": .entertainment, "sirius-xm": .entertainment,
        // Tools — software, dev, AI, storage, productivity, security, learning
        "icloud": .tools, "google-one": .tools, "dropbox": .tools, "adobe-cc": .tools,
        "adobe-photography": .tools, "github": .tools, "github-copilot": .tools, "chatgpt": .tools,
        "openai": .tools, "claude": .tools, "anthropic": .tools, "gemini": .tools,
        "perplexity": .tools, "cursor": .tools, "replit": .tools, "vercel": .tools, "v0": .tools,
        "bolt": .tools, "lovable": .tools, "linear": .tools, "suno": .tools, "elevenlabs": .tools,
        "huggingface": .tools, "deepseek": .tools, "notion": .tools, "lastpass": .tools,
        "1password": .tools, "expressvpn": .tools, "nordvpn": .tools, "microsoft-365": .tools,
        "duolingo": .tools, "masterclass": .tools,
        // Health — fitness, wellness
        "peloton": .health, "headspace": .health, "calm": .health, "noom": .health,
        "planet-fitness": .health, "equinox": .health,
        // News
        "nyt": .news, "wsj": .news, "washington-post": .news,
        // Shopping — retail memberships, delivery
        "amazon-prime": .shopping, "walmart-plus": .shopping, "uber-one": .shopping,
        "lyft-pink": .shopping, "dashpass": .shopping, "instacart-plus": .shopping, "grubhub-plus": .shopping,
        // Added 2026-09: platform billers, split-out brands, streaming long tail
        "apple-services": .entertainment, "apple-one": .entertainment, "apple-arcade": .entertainment,
        "apple-news": .news, "apple-fitness": .health, "google-play": .entertainment,
        "google-workspace": .tools, "adobe": .tools, "midjourney": .tools, "runway": .tools,
        "mistral": .tools, "cohere": .tools, "prime-video": .entertainment, "amazon-music": .entertainment,
        "kindle-unlimited": .entertainment, "amazon-digital": .entertainment, "youtube-music": .entertainment,
        "crunchyroll": .entertainment, "espn-plus": .entertainment, "starz": .entertainment,
        "amc-plus": .entertainment, "fubo": .entertainment, "sling": .entertainment, "philo": .entertainment,
        "pandora": .entertainment, "bitwarden": .tools, "proton-vpn": .tools, "proton": .tools,
        "apple-passwords": .tools,
    ]

    private static let knownDisplayNames: [String: String] = [
        // Streaming
        "netflix": "Netflix",
        "hulu": "Hulu",
        "spotify": "Spotify",
        "peacock": "Peacock",
        "paramount": "Paramount+",
        "paramount-plus": "Paramount+",
        "disney-plus": "Disney+",
        "hbo-max": "Max",
        "apple-tv": "Apple TV+",
        "apple-music": "Apple Music",
        "tidal": "Tidal",
        "audible": "Audible",
        "amazon-prime": "Amazon Prime",
        "walmart-plus": "Walmart+",
        "icloud": "iCloud+",
        "google-one": "Google One",
        "dropbox": "Dropbox",
        "adobe-cc": "Adobe Creative Cloud",
        "adobe-photography": "Adobe Photography",
        "github": "GitHub",
        "github-copilot": "GitHub Copilot",
        "chatgpt": "ChatGPT",
        "openai": "OpenAI",
        "claude": "Claude",
        "anthropic": "Anthropic",
        "gemini": "Gemini",
        "perplexity": "Perplexity",
        "cursor": "Cursor",
        "replit": "Replit",
        "vercel": "Vercel",
        "v0": "v0",
        "bolt": "Bolt",
        "lovable": "Lovable",
        "linear": "Linear",
        "suno": "Suno",
        "elevenlabs": "ElevenLabs",
        "huggingface": "Hugging Face",
        "deepseek": "DeepSeek",
        "notion": "Notion",
        "duolingo": "Duolingo",
        "lastpass": "LastPass",
        "1password": "1Password",
        "expressvpn": "ExpressVPN",
        "nordvpn": "NordVPN",
        "nyt": "The New York Times",
        "peloton": "Peloton",
        "headspace": "Headspace",
        "youtube-premium": "YouTube Premium",
        "youtube-tv": "YouTube TV",
        // Mobility / delivery memberships
        "uber-one": "Uber One",
        "lyft-pink": "Lyft Pink",
        "dashpass": "DashPass",
        // No-SVG brands
        "planet-fitness": "Planet Fitness",
        "equinox": "Equinox",
        "masterclass": "MasterClass",
        "wsj": "The Wall Street Journal",
        "washington-post": "The Washington Post",
        "sirius-xm": "SiriusXM",
        "calm": "Calm",
        "noom": "Noom",
        // Cable / wireless
        "spectrum": "Spectrum",
        "xfinity": "Xfinity",
        "t-mobile": "T-Mobile",
        "verizon": "Verizon",
        "att": "AT&T",
        // Platform billers / split-out brands (2026-09)
        "apple-services": "Apple (App Store)",
        "apple-one": "Apple One",
        "apple-arcade": "Apple Arcade",
        "apple-news": "Apple News+",
        "apple-fitness": "Apple Fitness+",
        "google-play": "Google Play",
        "google-workspace": "Google Workspace",
        "microsoft-365": "Microsoft 365",
        "adobe": "Adobe",
        "midjourney": "Midjourney",
        "runway": "Runway",
        "mistral": "Mistral",
        "cohere": "Cohere",
        "prime-video": "Prime Video",
        "amazon-music": "Amazon Music",
        "kindle-unlimited": "Kindle Unlimited",
        "amazon-digital": "Amazon Digital",
        "youtube-music": "YouTube Music",
        "instacart-plus": "Instacart+",
        "grubhub-plus": "Grubhub+",
        "crunchyroll": "Crunchyroll",
        "espn-plus": "ESPN",
        "starz": "Starz",
        "amc-plus": "AMC+",
        "fubo": "Fubo",
        "sling": "Sling TV",
        "philo": "Philo",
        "pandora": "Pandora",
        "bitwarden": "Bitwarden",
        "proton-vpn": "Proton VPN",
        "proton": "Proton",
        "apple-passwords": "Apple Passwords",
        // Verticals added 2026-09-11.
        "abcmouse": "ABCmouse", "acorn-tv": "Acorn TV", "arlo": "Arlo Secure", "aura": "Aura",
        "betterhelp": "BetterHelp", "bitdefender": "Bitdefender", "blinkist": "Blinkist",
        "bloomberg": "Bloomberg", "blue-apron": "Blue Apron", "bluehost": "Bluehost",
        "britbox": "BritBox", "bumble": "Bumble", "calendly": "Calendly", "canva": "Canva",
        "capcut": "CapCut", "classpass": "ClassPass", "coffee-meets-bagel": "Coffee Meets Bagel",
        "cookunity": "CookUnity", "copilot-money": "Copilot Money", "costco": "Costco",
        "criterion-channel": "The Criterion Channel", "curiositystream": "CuriosityStream",
        "cvs-carepass": "CVS CarePass", "dazn": "DAZN", "deezer": "Deezer", "deleteme": "DeleteMe",
        "descript": "Descript", "discord-nitro": "Discord Nitro", "epic-books": "Epic!",
        "everand": "Everand", "evernote": "Evernote", "factor": "Factor", "fastmail": "Fastmail",
        "figma": "Figma", "financial-times": "Financial Times", "fitbit-premium": "Fitbit Premium",
        "framer": "Framer", "geforce-now": "GeForce Now", "godaddy": "GoDaddy",
        "grammarly": "Grammarly", "green-chef": "Green Chef", "grindr": "Grindr",
        "hellofresh": "HelloFresh", "hers": "Hers", "hims": "Hims", "hinge": "Hinge",
        "home-chef": "Home Chef", "hostinger": "Hostinger", "incogni": "Incogni", "ko-fi": "Ko-fi",
        "libro-fm": "Libro.fm", "lifelock": "LifeLock", "linkedin-premium": "LinkedIn Premium",
        "malwarebytes": "Malwarebytes", "marley-spoon": "Marley Spoon", "match": "Match.com",
        "mcafee": "McAfee", "mister-car-wash": "Mister Car Wash", "mlb-tv": "MLB.TV",
        "monarch-money": "Monarch Money", "morningstar": "Morningstar", "mubi": "MUBI",
        "namecheap": "Namecheap", "nba-league-pass": "NBA League Pass", "nebula": "Nebula",
        "nest-aware": "Nest Aware", "nfl-plus": "NFL+",
        "nintendo-switch-online": "Nintendo Switch Online", "noggin": "Noggin",
        "norton": "Norton 360", "one-medical": "One Medical", "onstar": "OnStar",
        "otter-ai": "Otter.ai", "oura": "Oura", "patreon": "Patreon",
        "pixelmator": "Pixelmator Pro", "playstation-plus": "PlayStation Plus",
        "proton-mail": "Proton Mail", "qobuz": "Qobuz", "quickbooks": "QuickBooks",
        "quicken-simplifi": "Quicken Simplifi", "readwise": "Readwise",
        "reddit-premium": "Reddit Premium", "ring-home": "Ring Home",
        "roblox-premium": "Roblox Premium", "rocket-money": "Rocket Money",
        "sams-club": "Sam's Club", "seeking-alpha": "Seeking Alpha", "shopify": "Shopify",
        "shudder": "Shudder", "simplisafe": "SimpliSafe", "snapchat-plus": "Snapchat+",
        "speechify": "Speechify", "squarespace": "Squarespace", "strava": "Strava",
        "substack": "Substack", "superhuman": "Superhuman", "take-5-car-wash": "Take 5 Car Wash",
        "talkspace": "Talkspace", "the-athletic": "The Athletic", "the-atlantic": "The Atlantic",
        "the-economist": "The Economist", "the-new-yorker": "The New Yorker", "tinder": "Tinder",
        "todoist": "Todoist", "turbotax": "TurboTax", "twitch": "Twitch", "webflow": "Webflow",
        "weight-watchers": "WeightWatchers", "whoop": "WHOOP", "wix": "Wix",
        "wordpress": "WordPress.com", "wyze": "Wyze", "xbox-game-pass": "Xbox Game Pass",
        "ynab": "YNAB", "zips-car-wash": "Zips Car Wash",
        // Catalog merge 2026-09-11.
        "tubi": "Tubi",
        "pluto-tv": "Pluto TV",
        "roku-channel": "The Roku Channel",
        "kanopy": "Kanopy",
        "hoopla": "hoopla",
        "magellantv": "MagellanTV",
        "dropout": "Dropout",
        "hallmark-plus": "Hallmark+",
        "nordpass": "NordPass",
        "dashlane": "Dashlane",
        "affinity": "Affinity (by Canva)",
        "davinci-resolve": "DaVinci Resolve",
        "nike-training-club": "Nike Training Club",
        "google-news": "Google News",
        "proton-pass": "Proton Pass",
        "libby": "Libby",
        "insight-timer": "Insight Timer",
        "microsoft-copilot": "Microsoft Copilot",
        "windsurf": "Windsurf",
        "babbel": "Babbel",
        "busuu": "Busuu",
        "mullvad": "Mullvad",
        "skillshare": "Skillshare",
        "weightwatchers": "WeightWatchers (WW)",
        "obsidian": "Obsidian",
        "iheartradio": "iHeartRadio",
        // Catalog merge 2026-09-11.
        "waking-up": "Waking Up",
        "ten-percent-happier": "Happier (formerly Ten Percent Happier)",
        "balance": "Balance",
        "x-premium": "X Premium",
        "meta-verified": "Meta Verified",
        "telegram-premium": "Telegram Premium",
        "medium": "Medium",
        "open-path-collective": "Open Path Collective",
        "psychology-today-finder": "Psychology Today therapist finder",
        "dinnerly": "Dinnerly",
        "okcupid": "OkCupid",
        "peloton-app": "Peloton App",
        "slack": "Slack",
        "scruff": "SCRUFF",
        "feeld": "Feeld",
        "everyplate": "EveryPlate",
        "tasty": "Tasty",
        "goodrx": "GoodRx",
        "cost-plus-drugs": "Cost Plus Drugs",
        "buy-me-a-coffee": "Buy Me a Coffee",
        "indeed": "Indeed",
        "glassdoor": "Glassdoor",
        "feedly": "Feedly",
        "cvs-minuteclinic": "CVS MinuteClinic",
        "apple-watch": "Apple Watch (built-in Health app)",
        "google-health-premium": "Google Health Premium (formerly Fitbit Premium)",
        "youtube": "YouTube",
        "brave-browser": "Brave Browser",
        "discord": "Discord",
        "instagram": "Instagram",
        "bereal": "BeReal",
        "nike-run-club": "Nike Run Club",
        "garmin-connect": "Garmin Connect",
        "signal": "Signal",
        "whatsapp": "WhatsApp",
        "kick": "Kick",
        "myfitnesspal": "MyFitnessPal",
        "bluesky": "Bluesky",
        "threads": "Threads",
        "mastodon": "Mastodon",
        // Catalog merge 2026-09-11.
        "tesla-premium-connectivity": "Tesla Premium Connectivity",
        "lingokids": "Lingokids",
        "homer": "HOMER",
        "bjs": "BJ's Wholesale Club",
        "target-circle-360": "Target Circle 360",
        "khan-academy-kids": "Khan Academy Kids",
        "pbs-kids": "PBS Kids",
        "eufy": "Eufy",
        "cvs-extracare": "CVS ExtraCare (free tier)",
        "aaa": "AAA",
        "adt": "ADT",
        "target-circle": "Target Circle (free tier)",
        "tesla-standard-connectivity": "Tesla Standard Connectivity",
        // Catalog merge 2026-09-11.
        "hey": "HEY",
        "tuta": "Tuta",
        "simplelogin": "SimpleLogin",
        "free-credit-freeze": "Free credit freeze (Equifax, Experian, TransUnion)",
        "builtin-os-protection": "Windows Security / Apple built-in protection",
        "empower": "Empower Personal Dashboard",
        "ca-drop": "California DROP (Delete Request and Opt-Out Platform)",
        "gmail": "Gmail",
        "credit-karma": "Credit Karma",
        "yahoo-finance": "Yahoo Finance",
        "fidelity": "Fidelity Research Center",
        "firefox-relay": "Firefox Relay",
        "freetaxusa": "FreeTaxUSA",
        "cash-app-taxes": "Cash App Taxes",
        "irs-free-file": "IRS Free File",
    ]
}
