import Foundation

enum DisputeReason: String, CaseIterable, Identifiable {
    case forgottenTrial
    case autoRenewalNoNotice
    case cancelledStillCharged
    case unauthorizedCharge
    case priceHikeNoNotice

    var id: String { rawValue }

    var label: String {
        switch self {
        case .forgottenTrial:        return "Trial converted without notice"
        case .autoRenewalNoNotice:   return "Auto-renewed without warning"
        case .cancelledStillCharged: return "Cancelled but still charged"
        case .unauthorizedCharge:    return "I never authorized this"
        case .priceHikeNoNotice:     return "Price raised without notice"
        }
    }

    var subtext: String {
        switch self {
        case .forgottenTrial:        return "Free trial silently became a paid charge"
        case .autoRenewalNoNotice:   return "Annual or monthly renewal not disclosed"
        case .cancelledStillCharged: return "Service was cancelled — charge still appeared"
        case .unauthorizedCharge:    return "No record of signing up"
        case .priceHikeNoNotice:     return "New price was not disclosed in advance"
        }
    }

    var phrase: String {
        switch self {
        case .forgottenTrial:
            return "The charge stems from a free trial that converted into a paid subscription without clear, conspicuous notice as required under the Restore Online Shoppers' Confidence Act (ROSCA, 15 U.S.C. § 8403)."
        case .autoRenewalNoNotice:
            return "The renewal was processed without advance notification, in conflict with California's Automatic Renewal Law (Cal. Bus. & Prof. Code §§ 17600–17606) and equivalent statutes in 22 other states."
        case .cancelledStillCharged:
            return "I cancelled this service prior to the billing date, yet the charge still appeared on my statement. Under the Electronic Fund Transfer Act (15 U.S.C. § 1693f), unauthorized post-cancellation debits must be reversed."
        case .unauthorizedCharge:
            return "I have no record of authorizing this subscription. Under 12 C.F.R. § 1005.6 (Regulation E), this constitutes an unauthorized electronic fund transfer and must be refunded."
        case .priceHikeNoNotice:
            return "The price was raised without the legally required 30-day advance notice. Under the FTC's Negative Option Rule, material changes to subscription terms require affirmative consent."
        }
    }

    var successRate: Int {
        switch self {
        case .forgottenTrial:        return 73
        case .autoRenewalNoNotice:   return 64
        case .cancelledStillCharged: return 86
        case .unauthorizedCharge:    return 91
        case .priceHikeNoNotice:     return 52
        }
    }
}

struct DisputeForm {
    var fullName: String = "Jordan Lee"
    var email: String = "jordan@subspy.com"
    var chargeDate: String
    var amount: Double
    var reason: DisputeReason = .forgottenTrial
    var referenceNumber: String = ""
}

enum DisputeLetter {
    static func generate(for sub: Subscription, form: DisputeForm) -> String {
        let today: String = {
            let f = DateFormatter()
            f.locale = Locale(identifier: "en_US")
            f.dateFormat = "MMMM d, yyyy"
            return f.string(from: Date())
        }()
        let amount = fmtUSD(form.amount)
        let ref = form.referenceNumber.isEmpty
            ? ""
            : "\nReference / Transaction ID: \(form.referenceNumber)"

        return """
        \(today)

        \(sub.vendor)
        Billing Disputes Department
        Re: Refund request — \(sub.name)

        To Whom It May Concern,

        I am writing to formally dispute a charge of \(amount) dated \(form.chargeDate), billed to my account by \(sub.vendor) for "\(sub.name)".\(ref)

        \(form.reason.phrase)

        Accordingly, I respectfully request a full refund of \(amount) to the original payment method within 10 business days of receipt of this letter. Please confirm in writing once the refund has been processed.

        If a refund is not issued within that window, I will pursue the matter further through:
          • A formal chargeback request with my card issuer under Regulation Z (15 U.S.C. § 1666).
          • A complaint filed with the Federal Trade Commission (ftc.gov/complaint).
          • A complaint filed with the Consumer Financial Protection Bureau (consumerfinance.gov/complaint).
          • A complaint filed with my state Attorney General's office.

        I trust this can be resolved amicably and promptly. I appreciate your attention to this matter.

        Sincerely,

        \(form.fullName)
        \(form.email)

        — Generated by SubSpy on behalf of \(form.fullName). SubSpy does not file disputes on the user's behalf without explicit authorization.
        """
    }
}
